# Generated by Django 4.0 on 2021-12-16 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='one_text',
            field=models.CharField(default='uno', max_length=200),
        ),
    ]
