# Generated by Django 4.0 on 2021-12-17 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articulos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Articulo', models.CharField(max_length=150)),
                ('Description', models.TextField()),
                ('Cantidad', models.IntegerField(default=0)),
            ],
        ),
    ]
